Autocommit por Git-Cron: alterações: add '.config/rofi/scripts/screenshot'

diff --git a/.config/rofi/scripts/screenshot b/.config/rofi/scripts/screenshot
--- a/.config/rofi/scripts/screenshot
+++ b/.config/rofi/scripts/screenshot
@@ -11,6 +11,8 @@ icone="/usr/share/icons/Arc/devices/24@2x/video-display.png"
 tema="~/.local/share/rofi/themes/dark.rasi"
 editor="gimp"
 
+command -v $app >/dev/null 2>&1 || { echo >&2 "Instale o programa: $app antes. Abortando..."; exit 1; }
+
 if [ ! -d $dir ]; then
 	mkdir -p $dir
 fi
